services:
  postgres-ead:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "ead"
    networks:
      - networkEad
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "15432:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - postgres-ead
    networks:
      - networkEad
networks:
  networkEad:
    driver: bridge